### ISSUE TITLE
Oops, An expected error seems to have occurred.

### ISSUE THREAD

**Issue by 4n70w4** [zenato/puppeteer-renderer#27]
```
Error: net::ERR_CERT_AUTHORITY_INVALID at https://localhost/c5934.html
    at navigate (/app/node_modules/puppeteer/lib/FrameManager.js:108:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:105:23)
    at Page.goto (/app/node_modules/puppeteer/lib/Page.js:615:53)
    at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:106:31)
    at Renderer.createPage (/app/src/renderer.js:22:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by 4n70w4** [comment]
Okay, need add `-e IGNORE_HTTPS_ERRORS=true`

```
docker run -p 3000:3000 -e IGNORE_HTTPS_ERRORS=true zenato/puppeteer-renderer
```
