### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Page crashed!

### ISSUE THREAD

**Issue by DiskoPete** [zenato/puppeteer-renderer#34]
I ran into this issue and was wondering if this problem is already known.

```
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 178)
(node:25) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.Page.client.on (/app/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (events.js:189:13)
    at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocketTransport._ws.addEventListener (/app/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:189:13)
```

Once the error is thrown it won't 'recover' and throw the same error until I restart the docker container.

According to this issues it's related to too small shared memory files:\
https://github.com/puppeteer/puppeteer/issues/1321\
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#tips

I haven't debugged the problem thoroughly but It should be solved with this simple flag.

```
const browser = await puppeteer.launch({
  args: ['--disable-dev-shm-usage']
});
```

If you think it's a good idea, I am happy to prepare a pull request.

Thanks!

**Comment by zenato** [comment]
@DiskoPete Thanks your error report.

I don't recommend adding the above options as default.
See the discussion below.
https://github.com/puppeteer/puppeteer/issues/1834

However, you can expect the same effect with the command below.
```
docker run --shm-size=1gb ...
```

**Comment by DiskoPete** [comment]
Thanks for your feedback!

I will close this then
