### ISSUE TITLE
Expected options.clip.x to be a number but found undefined

### ISSUE THREAD

**Issue by seigieu** [zenato/puppeteer-renderer#41]
As in title

```
Error: Expected options.clip.x to be a number but found undefined
at Object.exports.assert (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
at Page.screenshot (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1070:25)
at Renderer.screenshot (/app/src/renderer.js:120:33)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async /app/src/index.js:64:44
```

Maybe last fix for #36 broke something?

**Comment by seigieu** [comment]
@zenato Actually, tried to set it to 0. There is whole chain now
```
Error: Expected options.clip.x to be a number but found undefined
Error: Expected options.clip.y to be a number but found undefined
Error: Expected options.clip.width to be a number but found undefined
Error: Expected options.clip.height to be a number but found undefined
```
And after all are set it works again.

**Comment by zenato** [comment]
@seigieu Fixed validation rules.
And if you want to use clipping, you should pass all property in clip. (clip.x, clip.y, clip.width, clip.height)
Thanks for your report.
