### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by MiguelAngelLV** [zenato/puppeteer-renderer#5]
Fresh instalation failed
```
renderer    | 
renderer    | > puppeteer-renderer@0.1.0 start /app
renderer    | > node src/index.js
renderer    | 
renderer    | Fail to initialze renderer. Error: Failed to launch chrome!
renderer    | /app/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
renderer    | 
renderer    | 
renderer    | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
renderer    | 
renderer    |     at onClose (/app/node_modules/puppeteer/lib/Launcher.js:211:14)
renderer    |     at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:200:50)
renderer    |     at emitNone (events.js:111:20)
renderer    |     at Interface.emit (events.js:208:7)
renderer    |     at Interface.close (readline.js:370:8)
renderer    |     at Socket.onend (readline.js:149:10)
renderer    |     at emitNone (events.js:111:20)
renderer    |     at Socket.emit (events.js:208:7)
renderer    |     at endReadableNT (_stream_readable.js:1064:12)
renderer    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)

```

**Comment by zenato** [comment]
@MiguelAngelLV 
Did you run docker image? I ran docker image and It worked well.
`docker run -d --name renderer -p 8080:3000 zenato/puppeteer-renderer`

Also, I ran without docker, It worked well too.
`npm install && npm run start`

How did you run?
Please tell me your detail environment.

**Comment by seguins** [comment]
This error seems to be related to the chrome dependencies.
You should try to follow the[ installation of puppeteer for Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker).

If your package manager is apt, you can start by installing libgconf-2 : `apt-get update && apt-get install -yq libgconf-2-4`

**Comment by zenato** [comment]
I had no idea because I was running on OSX.
@seguins Thanks for your answer.
