### ISSUE TITLE
Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by ryancom16** [zenato/puppeteer-renderer#71]
Error with latest update 2.4.2
Container fails to start
Reverting back to 2.4.0 solves the issue

```
Error: Cannot find module 'fs/promises'
Require stack:
- /app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js
- /app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js
- /app/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js
- /app/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
- /app/src/renderer.js
- /app/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:36:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js',
    '/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js',
    '/app/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js',
    '/app/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js',
    '/app/src/renderer.js',
    '/app/src/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer-renderer@2.4.2 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer-renderer@2.4.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by zenato** [comment]
@ryancom16 I deployed a fresh docker image and verified that it works fine in a linux environment.
